### ISSUE TITLE
Cannot load css/js resources when using reverse proxy

### ISSUE THREAD

**Issue by xtiancapil** [scottie1984/swagger-ui-express#111]
We recently moved to using a reverse-proxy to serve our swagger-ui and it seems to have broken loading the necessary css/js files to get the site to work. It seems to be loading the index.html page instead of the actual resources. Any idea how to go about fixing this?

![image](https://user-images.githubusercontent.com/460911/52094673-e29ec200-2574-11e9-810b-b056cf98c6d9.png)

**Comment by scottie1984** [comment]
Hey - I don't believe there should be anything specific in this module that would stop it working behind a reverse proxy. My only suggestion is the proxy is not configured correctly. Do other endpoints work OK? 

I would place some middleware to log all the requests in the Express server to see how the requests are being received by Express. Also look at the requests made by the browser for the resources - does this give you a clue as to what is going on.

SImilar issue here [https://github.com/springfox/springfox/issues/1330](https://github.com/springfox/springfox/issues/1330)

Sorry I couldn't help more but it seems like a proxy issue rather than with this module.

**Comment by xtiancapil** [comment]
Whenever my reverse proxy was set to just proxy from the root path '/', everything worked fine.
When i switch my reverse proxy to forward calls on '/swagger' (something other than root, then it stops working). It serves the index file correctly but is unable to retrieve any of the static files.

In the meantime, I had a look at index.js and it seems to be looking for 'swagger-ui-init.js' at the root level (if i'm interpreting it correctly).
https://github.com/scottie1984/swagger-ui-express/blob/master/index.js#L75
https://github.com/scottie1984/swagger-ui-express/blob/master/index.js#L63

I changed both lines to check for the indexOf swagger-ui-init.js and it was able to serve it properly, both under '/' and '/swagger' reverse proxy.

I also modified this script resources and added a prefix to the paths:
https://github.com/scottie1984/swagger-ui-express/blob/master/indexTemplate.html#L69
https://github.com/scottie1984/swagger-ui-express/blob/master/indexTemplate.html#L70
https://github.com/scottie1984/swagger-ui-express/blob/master/indexTemplate.html#L71

So instead of './swagger-ui-bundle.js' it would be '/swagger/swagger-ui-bundle.js'

That seems to have done the trick but I had to modify the distributed files. I will try your suggestions and see if those work. Thanks.

**Comment by scottie1984** [comment]
Maybe this will help [https://serverfault.com/questions/562756/how-to-remove-the-path-with-an-nginx-proxy-pass](https://serverfault.com/questions/562756/how-to-remove-the-path-with-an-nginx-proxy-pass).

Ultimately I think you want to proxy to not pass on /swagger to your Express server
