### ISSUE TITLE
 Disable Try it Out button 

### ISSUE THREAD

**Issue by ReshmaSuresh** [scottie1984/swagger-ui-express#120]
This is more of a question. How could the `Try it Out` button be disabled ?

**Comment by scottie1984** [comment]
Based on [https://github.com/swagger-api/swagger-ui/issues/3725#issuecomment-334899276](https://github.com/swagger-api/swagger-ui/issues/3725#issuecomment-334899276)

```javascript
const DisableTryItOutPlugin = function() {
  return {
    statePlugins: {
      spec: {
        wrapSelectors: {
          allowTryItOutFor: () => () => false
        }
      }
    }
  }
}

var options = {
  swaggerOptions: {
      plugins: [
           DisableTryItOutPlugin
      ]
   }
};
```

**Comment by samirhinojosa** [comment]
Hi @scottie1984 , I'm new to all this, could you please tell where should I put this code? Thanks!

**Comment by scottie1984** [comment]
```javascript
const express = require('express');
const app = express();
const swaggerUi = require('swagger-ui-express');
const swaggerDocument = require('./swagger.json');

const DisableTryItOutPlugin = function() {
  return {
    statePlugins: {
      spec: {
        wrapSelectors: {
          allowTryItOutFor: () => () => false
        }
      }
    }
  }
}

const options = {
  swaggerOptions: {
      plugins: [
           DisableTryItOutPlugin
      ]
   }
};
 
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument, options));
```

Hope that helps

**Comment by ReshmaSuresh** [comment]
Closing this thread

**Comment by JonEG** [comment]
> ```js
> const express = require('express');
> const app = express();
> const swaggerUi = require('swagger-ui-express');
> const swaggerDocument = require('./swagger.json');
> 
> const DisableTryItOutPlugin = function() {
>   return {
>     statePlugins: {
>       spec: {
>         wrapSelectors: {
>           allowTryItOutFor: () => () => false
>         }
>       }
>     }
>   }
> }
> 
> const options = {
>   swaggerOptions: {
>       plugins: [
>            DisableTryItOutPlugin
>       ]
>    }
> };
>  
> app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument, options));
> ```
> 
> Hope that helps

```
const options = {
  swaggerOptions: {
    supportedSubmitMethods: []
   }
};

app.use("/api-docs", swaggerUi.serve, swaggerUi.setup(require('./docs/build.json'),options));
```

**Comment by talkohavy** [comment]
Hey, **i'm opening this issue up and raising it again**.

Since the time this solution was presented here,
the **`Swagger UI`** folks created a **_built-in option to disable the "try it out"_** button altogether.
[Here](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#user-content-tryitoutenabled) is a reference to their doc which includes this option, and here's the thread (THE SAME ONE that raised that plugin work-around fix) with a comment down at the very bottom that says _"hey, this work-around plugin thingy is no longer needed, since it is now built-in"_, and [here's another](https://github.com/swagger-api/swagger-ui/issues/6528#issuecomment-785837911).

I would love to see the support from the `swagger-ui-express` side as well! ❤️

Could it please be implemented here as well?

**Comment by scottie1984** [comment]
Those options can be set already via the swaggerOptions and will be passed through to swagger-ui:

https://github.com/scottie1984/swagger-ui-express#custom-swagger-options
