### ISSUE TITLE
Illegal token in javascript file

### ISSUE THREAD

**Issue by h0ru5** [scottie1984/swagger-ui-express#121]
a lot of processing tools stumbled over this line:

https://github.com/scottie1984/swagger-ui-express/blob/80030ffe35a36e235dbfc1d1a79046cf9c2e308d/swagger-ui-init.js#L9

it's not legal javascript and I do not get what is does, is it just a comment?

**Comment by scottie1984** [comment]
The file is a template and this line is replaced in memory

**Comment by shockey** [comment]
Might I suggest using a different file extension, e.g. `swagger-ui-init.js.tpl` or something like that.

@h0ru5, I'm surprised that a tool is coming across this file at all, since it's not in the module dependency graph for anything in swagger-ui-express. Can you elaborate on how you bumped up against this?

**Comment by shockey** [comment]
@scottie1984, might I suggest using a different file extension, e.g. `swagger-ui-init.js.tpl` or something like that. Technically `.js` is only supposed to be used for files parseable as JavaScript, though I've broken this rule many times as well...

@h0ru5, I'm surprised that a tool is coming across this file at all, since it's not in the module dependency graph for anything in swagger-ui-express. Can you elaborate on how you bumped up against this?

**Comment by scottie1984** [comment]
@shockey - yes, good idea. I will add that to the next release.

**Comment by h0ru5** [comment]
> @h0ru5, I'm surprised that a tool is coming across this file at all, since it's not in the module dependency graph for anything in swagger-ui-express. Can you elaborate on how you bumped up against this?

IIRC It was appearing when I was creating a solid optimized js file for easier distribution, which crawls the dep tree. I can double-check if it maybe was from globbing something like `dist/**/*.js`, which runs into node_modules. However, adding an extension should help in that case.
