### ISSUE TITLE
Express should be a dependency and not a devDependency

### ISSUE THREAD

**Issue by RDeluxe** [scottie1984/swagger-ui-express#145]
Hello,

I'm currently giving [PNPM](https://pnpm.js.org/) and [Rush.js](https://rushjs.io/) a try, and PNPM is stricter that NPM when it comes to dependency resolution.

In my case, it seems that because express is not listed as a dependency swagger-ui-express simply won't work at runtime. 

It seems to make sense to put express in the dependencies array, as libs like @nestjs/Swagger use swagger-ui-express at runtime.

**Comment by shockey** [comment]
Since `swagger-ui-express` is used within Express applications, I'd expect `express` to already be in the consuming application's production dependency tree. (Perhaps `express` should be a [`peerDependency`](http://npm.github.io/using-pkgs-docs/package-json/types/peerdependencies.html).)

If this module were to declare `express` in `dependencies`, users could end up in a situation where two different versions of `express` are in their dependency tree, which could cause problems.

---

For `@nestjs/swagger`'s part, I don't see `swagger-ui-express` [in their package manifest](https://github.com/nestjs/swagger/blob/master/package.json#L17-L38). Can you share what you're referring to?

**Comment by RDeluxe** [comment]
Hello,

I see your point, then you should add express to peerDependencies I think, as it is still a runtime dep and not a dev one.

In general, for pure strictness, it's better not to rely on the "flattened" node_modules. I think yarn PnP may have trouble too.

@zkochan explains it really well here => https://medium.com/pnpm/pnpms-strictness-helps-to-avoid-silly-bugs-9a15fb306308

**Comment by RDeluxe** [comment]
I created a PR, we may discuss this topic there ? #146

**Comment by hbobenicio** [comment]
The PR was already merged and the express package is already a peerDependency.

I think this issue is already solved, isn't it?

@scottie1984

**Comment by scottie1984** [comment]
The PR has been merged however I haven't published to NPM yet.
