### ISSUE TITLE
'url' in the swagger options is ignored

### ISSUE THREAD

**Issue by benny-hal** [scottie1984/swagger-ui-express#20]
in the swaggerOptions the keys 'spec' is always set. So if the 'url' is set as an extra option it is ignored, as the swagger ui ignores 'url' when 'spec' exists. 

This means its not possible to get the swagger ui to display the link to the swagger definition as the link to the swagger definition is only shown when 'url' is set and 'spec' is not set....

**Comment by scottie1984** [comment]
I think this is an issue with Swagger UI as we always set the URL property. One way to resolve is put the url in the querystring:

http://localhost:3000/api-docs/?url=http://localhost:3000/swagger.json 

It looks like Swagger UI will only display the link if the url in the query string is set.

**Comment by skray** [comment]
I'm having another issue due to this, namely that I cannot use relative `$ref` paths in my Swagger due to how swagger-ui (and therefore swagger-js) does not parse the `url` if the `spec` option is set. Specifically, it throws the error ["Tried to resolve a relative URL, without having a basePath"](https://github.com/swagger-api/swagger-js/blob/master/src/specmap/lib/refs.js#L153). I think this makes sense, as the documentation for the `spec` option states that is meant to be used "for testing manually-generated specifications without hosting them."

Would you be open to a PR that would allow for setting the `url` option explicitly, and when doing so the `spec` option would be omitted from the `SwaggerUIBundle` constructor options?

**Comment by scottie1984** [comment]
@skray yes - I would be open for a PR as you described.
