### ISSUE TITLE
Model Schema not showing

### ISSUE THREAD

**Issue by nickelswitte** [scottie1984/swagger-ui-express#207]
I am using [swagger-ui-express](https://www.npmjs.com/package/swagger-ui-express) together with [swagger-jsdoc](https://www.npmjs.com/package/swagger-jsdoc).

When following this [example](https://github.com/Surnet/swagger-jsdoc/blob/HEAD/docs/GETTING-STARTED.md), it is working correctly most of the time, but schemas are not shown.

I am using Typescript with node.js and in my `tests.ts` file, like in the guide I define

```ts
/**
 * @swagger
 *
 * definitions:
 *   NewUser:
 *     type: object
 *     required:
 *       - username
 *       - password
 *     properties:
 *       username:
 *         type: string
 *       password:
 *         type: string
 *         format: password
 *   User:
 *     allOf:
 *       - $ref: '#/definitions/NewUser'
 *       - required:
 *         - id
 *       - properties:
 *         id:
 *           type: integer
 *           format: int64
 */

/**
 * @swagger
 * /users:
 *   get:
 *     description: Returns users
 *     produces:
 *      - routerlication/json
 *     responses:
 *       200:
 *         description: users
 *         schema:
 *           type: array
 *           items:
 *             $ref: '#/definitions/NewUser'
 */
router.get('/users', (req, res) => {
    // Your implementation logic comes here ...
});
```

But the model is never shown like in examples from https://editor.swagger.io/ or similar. For this, look at the picture.
![image](https://user-images.githubusercontent.com/36443026/89393992-cd779600-d70b-11ea-8bae-218fb6dddd2c.png)

Any advice?

**Comment by nickelswitte** [comment]
It might be of interest to add, that it works for parameters in this POST example.
![image](https://user-images.githubusercontent.com/36443026/89394514-74f4c880-d70c-11ea-864b-daf218766644.png)

**Comment by fmunirdev** [comment]
I'm facing almost the same issue. When I try to expand the request definition, it doesn't expand and change the tag to default. Everything works perfectly fine when I load the json/yml file in the online swagger editor.

**Comment by scottie1984** [comment]
Before passing the swagger doc to this module are you able to print it out and check that it looks correct and has all the definitions?

**Comment by scottie1984** [comment]
https://github.com/scottie1984/swagger-ui-express/issues/69

**Comment by asarver** [comment]
it looks specific to the `allOf` option. I'm seeing the same thing if I have schemas that use it

**Comment by JoffrayBillon** [comment]
[swagger-jsdoc](https://www.npmjs.com/package/swagger-jsdoc) documentation is not only poor but their examples contains a lot of errors.

Please refer to official swagger [docs](https://swagger.io/docs/specification/).

In your specific case definitions are not made to be printed on the swagger-ui, schemas are, and schemas are only defined inside components.

So understanding this your code should look like this:
````
/**
 * @swagger
 * components:
 *   schemas:
 *     NewUser:
 *       type: object
 *       required:
 *         - username
 *         - password
 *       properties:
 *         username:
 *           type: string
 *         password:
 *           type: string
 *           format: password
 */
````
And your `$ref` should now be changed to `#/components/schemas/NewUser`

Voilà !

**Comment by JoffrayBillon** [comment]
Correction: [swagger-jsdoc](https://www.npmjs.com/package/swagger-jsdoc) is not full of error, it's actually made for swagger: '2.0' so all the code is actually correct but you should change your swagger definition from `openapi: '3.0.3'` to `swagger: '2.0'`

As I said [here](https://github.com/scottie1984/swagger-ui-express/issues/189#issuecomment-738986346).

The solution I gave you earlier is not fully correct because you don't get the 'Example values' like that:
![image](https://user-images.githubusercontent.com/16031763/101210033-1d904600-3675-11eb-939f-7608669e81c2.png)
The $ref will not be resolved so instead you will see something like:
![image](https://user-images.githubusercontent.com/16031763/101210275-7f50b000-3675-11eb-8e39-8170ce1c58ab.png)
And I didn't have more time to figure out why and how to make it work.
Don't hesitate to ping me if you find the solution.
