### ISSUE TITLE
Is this package still being actively maintained?

### ISSUE THREAD

**Issue by seanCodes** [scottie1984/swagger-ui-express#250]
Hey @scottie1984, I realize there’s been some activity recently in this repo, but just wanted to double-check if this project was something you’re still actively maintaining. I noticed the code is getting a little dusty and thought it might be helpful to clean-up and modernize things (e.g. drop support for old node, migrate to ES6, replace PhantomJS with Puppeteer, etc.). Would you be open to some housekeeping-style PRs? If so, would the version-5 branch be the best place for those (or just master)?

I’d love to contribute if you’re up for it and happy to follow any guidelines you might have, but also don‘t want to add extra work to your plate if you’re busy! 👍🏽

**Comment by scottie1984** [comment]
Hey @seanCodes , please feel free to get involved. No real guidelines as such so please feel free to help in any way.

**Comment by scottie1984** [comment]
It was written originally in ES6 and then down to ES5 to support older versions of node. However I think things have changed significantly since then and we can put something in the readme for anyone using older versions of node to use and older version. Just against master is fine- I meant to delete the version5 branch as it wont be merged in
