### ISSUE TITLE
Changelog please

### ISSUE THREAD

**Issue by danielmcq** [scottie1984/swagger-ui-express#354]
To get to the point: why was the major version bumped recently? There is no changelog and the releases don't explain too much. It is obvious that the main dependency, swagger-ui-dist, has been updated. But that doesn't really explain much. Checking for changelogs on that project doesn't reveal too much either. I could keep digging and digging, but my request is that, at a minimum, a changelog is maintained. And any breaking changes are very easily identifiable. [Normally, when major version numbers are incremented, support for something gets dropped, ie a breaking change.](https://semver.org/)

**Comment by scottie1984** [comment]
Point taken. I went on the basis that as the main dependancy bumped to major i followed suit.

swagger-ui have felt the need to bump to major so rather than me potentially breaking someones app with a minor I bump to major as well.

i don’t think i have had any breaking changes since starting this project and major bumps have always been in line with swagger-ui-dist as that makes sense to me.

I will aim to add more to release notes in future.

**Comment by danielmcq** [comment]
I did notice the swagger-ui project bumping their major version. But I also had trouble finding release notes which indicate if any breaking changes.
Thank you for your work! This project makes my job easier by having less code that I have to maintain.
