### ISSUE TITLE
 x-csrf-token: Required 

### ISSUE THREAD

**Issue by kthelegend** [scottie1984/swagger-ui-express#47]
Hi @scottie1984 

For all the queries other than GET, we get the error message  **x-csrf-token: Required .** 

Currently the only workaround I found was updating the swagger specification with additional header to all POST, PUT, DELETE as x-csrf-token and manually fetch the token and pass it. 

Is there a better way of solving this issue? I could find there are a lot of topics / bugs around this in Internet but I couldn't find the right solution. Could you please help me? 

Best Regards,
Kishore Kumar

**Comment by scottie1984** [comment]
Looking at the swagger ui issues they suggest request interceptors as a way to deal with this issue:

[https://github.com/swagger-api/swagger-ui/issues/2793](https://github.com/swagger-api/swagger-ui/issues/2793)
[https://github.com/swagger-api/swagger-ui/issues/2896](https://github.com/swagger-api/swagger-ui/issues/2896)

You should be able to define requestInterceptor and responseInterceptor in the swaggerOptions property of the options that are passed into this module.

**Comment by kycrow32** [comment]
Leaving this here for the next poor soul who wants to support double-submit CSRF in their Node JS hosted swagger page.

The parameter, in swagger-ui-express 4.1.4 at least, is swaggerUiOptions.swaggerOptions.requestInterceptor.
The parameter type is a function.  Unfortunately, it is a function in Node that is copied into the UI, rather than a string or a file that is served up to the UI.  Which means your Node parser, linter, minifier, etc, are all going to have a go at that function.  What we wound up doing:

// We're going to inject a requestInterceptor into the swagger ui.
// But we do that using Javascript parsed and executed by Node, and not as Javascript wrapped in a string literal.
// So we need some dummy "document" variable to appease the linter.
// We also have to add 'document' to the reserved list for terser, so that it does not get minified.
const document = {
  cookie: 'dummy',
};
....
  const swaggerUiOptions = {
    swaggerOptions: {
      requestInterceptor: (request) => {
        const value = '; ' + document.cookie;
        const parts = value.split('; XSRF-TOKEN=');
        if (parts.length === 2) {
          request.headers['X-XSRF-TOKEN'] = parts.pop().split(';').shift();
        }
        return request;
      },
    },
  };
....
  const swaggerSetup = swaggerUi.setup(swaggerDocument, swaggerUiOptions, swaggerOptions);
